
import { MibNode, CollectorType, Device } from "../types";
import { generatorApi } from "./api";

/**
 * 通过后端 API 生成采集器配置
 */
export const generateConfigFromBackend = async (
  collector: CollectorType,
  version: string,
  nodes: MibNode[],
  community?: string,
  mibRoot?: string
): Promise<string> => {
  try {
    const response = await generatorApi.generateConfig({
      collector,
      version,
      nodes,
      community,
      mibRoot,
    });
    return response.config;
  } catch (error) {
    console.warn("后端配置生成失败，使用本地生成:", error);
    return generateLocalConfigBatch(collector, version, nodes);
  }
};

/**
 * 通过后端 API 生成 SDK 代码
 */
export const generateCodeFromBackend = async (
  node: MibNode,
  language: 'python' | 'javascript' | 'go' | 'java' | 'shell'
): Promise<string> => {
  try {
    const response = await generatorApi.generateCode({ node, language });
    return response.code;
  } catch (error) {
    console.warn("后端代码生成失败，使用本地生成:", error);
    return generateLocalSnmpCode(node, language);
  }
};

/**
 * 本地生成引擎（后备方案）：100% 离线运行
 */
export const generateLocalConfigBatch = (
  collector: CollectorType,
  version: string,
  nodes: MibNode[]
): string => {
  let output = "";
  const timestamp = new Date().toLocaleString();

  if (collector === 'snmp-exporter') {
    output = `# Generated by SNMP MIB Explorer (Local Engine)\n# Engine: ${collector} (${version})\n# Date: ${timestamp}\n\nmodules:\n  default:\n    walk:\n`;
    nodes.forEach(node => {
      output += `      - ${node.oid}  # ${node.name}\n`;
    });
    output += `\n    metrics:\n`;
    nodes.forEach(node => {
      const safeName = node.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
      output += `      - name: ${safeName}\n        oid: ${node.oid}\n        type: gauge\n        help: "${node.description || node.name}"\n`;
    });
    output += `\n    auth:\n      community: public\n`;
  } else if (collector === 'telegraf') {
    output = `# Telegraf SNMP Configuration\n# Version: ${version}\n# Date: ${timestamp}\n\n[[inputs.snmp]]\n  agents = ["udp://127.0.0.1:161"]\n  version = 2\n  community = "public"\n  interval = "60s"\n  name = "snmp"\n\n`;
    nodes.forEach(node => {
      const safeName = node.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
      output += `  [[inputs.snmp.field]]\n    name = "${safeName}"\n    oid = "${node.oid}"\n`;
    });
  } else if (collector === 'categraf') {
    output = `# Categraf SNMP Plugin Config\n# Version: ${version}\n# Date: ${timestamp}\n\n[[instances]]\n  interval = "60s"\n  agents = ["127.0.0.1:161"]\n  labels = { job = "snmp" }\n  community = "public"\n  version = 2\n\n`;
    nodes.forEach(node => {
      const safeName = node.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
      output += `  [[instances.field]]\n    name = "${safeName}"\n    oid = "${node.oid}"\n`;
    });
  }
  return output;
};

/**
 * 本地 SDK 代码生成模板（后备方案）
 */
export const generateLocalSnmpCode = (node: MibNode, language: string): string => {
  const templates: Record<string, string> = {
    python: `#!/usr/bin/env python3
"""SNMP Query for: ${node.name} (${node.oid})"""
from pysnmp.hlapi import *

def snmp_get(host, community, oid):
    iterator = getCmd(
        SnmpEngine(),
        CommunityData(community),
        UdpTransportTarget((host, 161)),
        ContextData(),
        ObjectType(ObjectIdentity(oid))
    )
    errorIndication, errorStatus, errorIndex, varBinds = next(iterator)
    if errorIndication:
        print(errorIndication)
    else:
        for varBind in varBinds:
            print(' = '.join([x.prettyPrint() for x in varBind]))

if __name__ == "__main__":
    snmp_get("127.0.0.1", "public", "${node.oid}")`,

    javascript: `// SNMP Query for: ${node.name} (${node.oid})
const snmp = require("net-snmp");

const session = snmp.createSession("127.0.0.1", "public");
const oids = ["${node.oid}"];

session.get(oids, (error, varbinds) => {
    if (error) {
        console.error(error);
    } else {
        varbinds.forEach(vb => {
            console.log(vb.oid + " = " + vb.value);
        });
    }
    session.close();
});`,

    go: `package main

// SNMP Query for: ${node.name} (${node.oid})
import (
	"fmt"
	"log"
	"time"
	"github.com/gosnmp/gosnmp"
)

func main() {
	gosnmp.Default.Target = "127.0.0.1"
	gosnmp.Default.Community = "public"
	gosnmp.Default.Timeout = time.Duration(10) * time.Second

	err := gosnmp.Default.Connect()
	if err != nil {
		log.Fatalf("Connect error: %v", err)
	}
	defer gosnmp.Default.Conn.Close()

	oids := []string{"${node.oid}"}
	result, err := gosnmp.Default.Get(oids)
	if err != nil {
		log.Fatalf("Get error: %v", err)
	}

	for _, v := range result.Variables {
		fmt.Printf("%s = %v\\n", v.Name, v.Value)
	}
}`,

    java: `// SNMP Query for: ${node.name} (${node.oid})
// Requires: snmp4j library
import org.snmp4j.*;
import org.snmp4j.smi.*;
import org.snmp4j.transport.DefaultUdpTransportMapping;

public class SnmpQuery {
    public static void main(String[] args) throws Exception {
        TransportMapping<?> transport = new DefaultUdpTransportMapping();
        transport.listen();
        Snmp snmp = new Snmp(transport);

        CommunityTarget<Address> target = new CommunityTarget<>();
        target.setCommunity(new OctetString("public"));
        target.setAddress(new UdpAddress("127.0.0.1/161"));
        target.setVersion(SnmpConstants.version2c);

        PDU pdu = new PDU();
        pdu.add(new VariableBinding(new OID("${node.oid}")));
        pdu.setType(PDU.GET);

        ResponseEvent<?> response = snmp.send(pdu, target);
        if (response.getResponse() != null) {
            for (VariableBinding vb : response.getResponse().getVariableBindings()) {
                System.out.println(vb.getOid() + " = " + vb.getVariable());
            }
        }
        snmp.close();
    }
}`,

    shell: `#!/bin/bash
# SNMP Query for: ${node.name} (${node.oid})

HOST="127.0.0.1"
COMMUNITY="public"
OID="${node.oid}"

echo "=== SNMP GET ==="
snmpget -v2c -c "$COMMUNITY" "$HOST" "$OID"

echo ""
echo "=== SNMP WALK ==="
snmpwalk -v2c -c "$COMMUNITY" "$HOST" "$OID"`
  };
  return templates[language] || `// No template available for ${language}`;
};

/**
 * 本地模拟 SNMP 测试响应
 */
export const simulateLocalSnmpTest = (device: Device, node: MibNode): string => {
  const randomValue = node.syntax?.toLowerCase().includes('integer')
    ? Math.floor(Math.random() * 100).toString()
    : "Active/OK";

  return `[TEST LOGS - ${new Date().toLocaleTimeString()}]\n` +
         `Target: ${device.ip}:${device.port}\n` +
         `OID: ${node.oid} (${node.name})\n` +
         `-----------------------------------\n` +
         `Response Value: ${randomValue}\n` +
         `Syntax Type: ${node.syntax || 'OctetString'}\n` +
         `Status: Success (Local Simulation Mode)`;
};
