package service

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"snmp-mib-explorer/internal/model"
)

type GeneratorService struct{}

func NewGeneratorService() *GeneratorService {
	return &GeneratorService{}
}

// DeviceInfo represents a device for config generation
type DeviceInfo struct {
	Name      string `json:"name"`
	IP        string `json:"ip"`
	Port      int    `json:"port"`
	Community string `json:"community"`
	Version   string `json:"version"`
}

type GenerateConfigRequest struct {
	Collector string           `json:"collector"` // snmp-exporter, telegraf, categraf
	Version   string           `json:"version"`
	Nodes     []model.MibNode  `json:"nodes"`
	Community string           `json:"community"`
	MibRoot   string           `json:"mibRoot"`
	Devices   []DeviceInfo     `json:"devices"` // Selected devices for telegraf/categraf
}

func (s *GeneratorService) GenerateConfig(req *GenerateConfigRequest) string {
	timestamp := time.Now().Format("2006-01-02 15:04:05")

	switch req.Collector {
	case "snmp-exporter":
		return s.generateSnmpExporter(req, timestamp)
	case "telegraf":
		return s.generateTelegraf(req, timestamp)
	case "categraf":
		return s.generateCategraf(req, timestamp)
	default:
		return fmt.Sprintf("# Unknown collector type: %s", req.Collector)
	}
}

func (s *GeneratorService) generateSnmpExporter(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# SNMP Exporter Configuration\n"))
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# MIB Root: %s\n", req.MibRoot))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("modules:\n")
	sb.WriteString("  default:\n")
	sb.WriteString("    walk:\n")

	for _, node := range req.Nodes {
		sb.WriteString(fmt.Sprintf("      - %s  # %s\n", node.OID, node.Name))
	}

	sb.WriteString("\n    metrics:\n")
	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		help := node.Description
		if help == "" {
			help = node.Name
		}
		// Escape quotes in help text
		help = strings.ReplaceAll(help, `"`, `\"`)

		sb.WriteString(fmt.Sprintf("      - name: %s\n", safeName))
		sb.WriteString(fmt.Sprintf("        oid: %s\n", node.OID))
		sb.WriteString(fmt.Sprintf("        type: gauge\n"))
		sb.WriteString(fmt.Sprintf("        help: \"%s\"\n", help))
	}

	sb.WriteString("\n    auth:\n")
	sb.WriteString("      community: " + community + "\n")

	return sb.String()
}

func (s *GeneratorService) generateTelegraf(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	// Build agents list from devices
	var agents []string
	if len(req.Devices) > 0 {
		for _, d := range req.Devices {
			port := d.Port
			if port == 0 {
				port = 161
			}
			agents = append(agents, fmt.Sprintf("\"udp://%s:%d\"", d.IP, port))
		}
		// Use first device's community if available
		if req.Devices[0].Community != "" {
			community = req.Devices[0].Community
		}
	} else {
		agents = []string{"\"udp://127.0.0.1:161\""}
	}

	var sb strings.Builder
	sb.WriteString("# Telegraf SNMP Input Configuration\n")
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# Devices: %d\n", len(req.Devices)))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("[[inputs.snmp]]\n")
	sb.WriteString("  ## Agent addresses to retrieve values from.\n")
	sb.WriteString(fmt.Sprintf("  agents = [%s]\n\n", strings.Join(agents, ", ")))
	sb.WriteString("  ## Timeout for each request.\n")
	sb.WriteString("  timeout = \"10s\"\n\n")
	sb.WriteString("  ## SNMP version; can be 1, 2, or 3.\n")
	sb.WriteString("  version = 2\n\n")
	sb.WriteString("  ## SNMP community string.\n")
	sb.WriteString(fmt.Sprintf("  community = \"%s\"\n\n", community))
	sb.WriteString("  ## Measurement name\n")
	sb.WriteString("  name = \"snmp\"\n\n")
	sb.WriteString("  ## Add fields to represent OID values\n")

	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		sb.WriteString(fmt.Sprintf("\n  [[inputs.snmp.field]]\n"))
		sb.WriteString(fmt.Sprintf("    name = \"%s\"\n", safeName))
		sb.WriteString(fmt.Sprintf("    oid = \"%s\"\n", node.OID))
		if node.Description != "" {
			sb.WriteString(fmt.Sprintf("    # %s\n", node.Description))
		}
	}

	sb.WriteString("\n  ## Add tables for table-based OIDs\n")
	sb.WriteString("  # [[inputs.snmp.table]]\n")
	sb.WriteString("  #   name = \"interface\"\n")
	sb.WriteString("  #   oid = \"IF-MIB::ifTable\"\n")

	return sb.String()
}

func (s *GeneratorService) generateCategraf(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	// Build agents list from devices
	var agents []string
	if len(req.Devices) > 0 {
		for _, d := range req.Devices {
			port := d.Port
			if port == 0 {
				port = 161
			}
			agents = append(agents, fmt.Sprintf("\"%s:%d\"", d.IP, port))
		}
		// Use first device's community if available
		if req.Devices[0].Community != "" {
			community = req.Devices[0].Community
		}
	} else {
		agents = []string{"\"127.0.0.1:161\""}
	}

	var sb strings.Builder
	sb.WriteString("# Categraf SNMP Plugin Configuration\n")
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# Devices: %d\n", len(req.Devices)))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("[[instances]]\n")
	sb.WriteString("  ## Interval for SNMP polling\n")
	sb.WriteString("  interval = \"60s\"\n\n")
	sb.WriteString("  ## Agent addresses\n")
	sb.WriteString(fmt.Sprintf("  agents = [%s]\n\n", strings.Join(agents, ", ")))
	sb.WriteString("  ## Timeout\n")
	sb.WriteString("  timeout = \"10s\"\n\n")
	sb.WriteString("  ## SNMP version (1, 2 for v2c, 3)\n")
	sb.WriteString("  version = 2\n\n")
	sb.WriteString("  ## Community string\n")
	sb.WriteString(fmt.Sprintf("  community = \"%s\"\n\n", community))
	sb.WriteString("  ## Labels to attach to all metrics\n")
	sb.WriteString("  labels = { job = \"snmp\" }\n\n")
	sb.WriteString("  ## Fields to collect\n")

	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		sb.WriteString(fmt.Sprintf("\n  [[instances.field]]\n"))
		sb.WriteString(fmt.Sprintf("    name = \"%s\"\n", safeName))
		sb.WriteString(fmt.Sprintf("    oid = \"%s\"\n", node.OID))
	}

	sb.WriteString("\n  ## Table-based collection (optional)\n")
	sb.WriteString("  # [[instances.table]]\n")
	sb.WriteString("  #   name = \"interface\"\n")
	sb.WriteString("  #   oid = \"1.3.6.1.2.1.2.2\"\n")

	return sb.String()
}

type GenerateCodeRequest struct {
	Node     model.MibNode `json:"node"`
	Language string        `json:"language"` // python, javascript, go, java, shell
}

func (s *GeneratorService) GenerateCode(req *GenerateCodeRequest) string {
	switch req.Language {
	case "python":
		return s.generatePython(&req.Node)
	case "javascript":
		return s.generateJavaScript(&req.Node)
	case "go":
		return s.generateGo(&req.Node)
	case "java":
		return s.generateJava(&req.Node)
	case "shell":
		return s.generateShell(&req.Node)
	default:
		return fmt.Sprintf("// Unsupported language: %s", req.Language)
	}
}

func (s *GeneratorService) generatePython(node *model.MibNode) string {
	return fmt.Sprintf(`#!/usr/bin/env python3
"""
SNMP Query for: %s
OID: %s
Generated by SNMP MIB Explorer
"""

from pysnmp.hlapi import *

def snmp_get(host, community, oid):
    """Perform SNMP GET operation"""
    iterator = getCmd(
        SnmpEngine(),
        CommunityData(community),
        UdpTransportTarget((host, 161), timeout=10, retries=3),
        ContextData(),
        ObjectType(ObjectIdentity(oid))
    )

    errorIndication, errorStatus, errorIndex, varBinds = next(iterator)

    if errorIndication:
        print(f"Error: {errorIndication}")
        return None
    elif errorStatus:
        print(f"Error: {errorStatus.prettyPrint()} at {errorIndex}")
        return None
    else:
        for varBind in varBinds:
            return varBind[1].prettyPrint()
    return None

def snmp_walk(host, community, oid):
    """Perform SNMP WALK operation"""
    results = []
    for (errorIndication, errorStatus, errorIndex, varBinds) in nextCmd(
        SnmpEngine(),
        CommunityData(community),
        UdpTransportTarget((host, 161), timeout=10, retries=3),
        ContextData(),
        ObjectType(ObjectIdentity(oid)),
        lexicographicMode=False
    ):
        if errorIndication:
            print(f"Error: {errorIndication}")
            break
        elif errorStatus:
            print(f"Error: {errorStatus.prettyPrint()}")
            break
        else:
            for varBind in varBinds:
                results.append({
                    'oid': varBind[0].prettyPrint(),
                    'value': varBind[1].prettyPrint()
                })
    return results

if __name__ == "__main__":
    HOST = "127.0.0.1"
    COMMUNITY = "public"
    OID = "%s"

    print(f"Querying {OID} ({node_name})...")
    result = snmp_get(HOST, COMMUNITY, OID)
    print(f"Result: {result}")
`, node.Name, node.OID, node.OID)
}

func (s *GeneratorService) generateJavaScript(node *model.MibNode) string {
	return fmt.Sprintf(`/**
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 */

const snmp = require("net-snmp");

const HOST = "127.0.0.1";
const COMMUNITY = "public";
const OID = "%s";

// Create SNMP session
const session = snmp.createSession(HOST, COMMUNITY, {
  port: 161,
  timeout: 10000,
  retries: 3,
  version: snmp.Version2c
});

// SNMP GET
function snmpGet(oid) {
  return new Promise((resolve, reject) => {
    session.get([oid], (error, varbinds) => {
      if (error) {
        reject(error);
      } else {
        const results = varbinds.map(vb => ({
          oid: vb.oid,
          type: snmp.ObjectType[vb.type],
          value: vb.value.toString()
        }));
        resolve(results);
      }
    });
  });
}

// SNMP WALK
function snmpWalk(oid) {
  return new Promise((resolve, reject) => {
    const results = [];
    session.walk(oid, 20, (varbinds) => {
      varbinds.forEach(vb => {
        results.push({
          oid: vb.oid,
          type: snmp.ObjectType[vb.type],
          value: vb.value.toString()
        });
      });
    }, (error) => {
      if (error) {
        reject(error);
      } else {
        resolve(results);
      }
    });
  });
}

// Main execution
async function main() {
  try {
    console.log("Querying " + OID + " (%s)...");
    const results = await snmpGet(OID);
    console.log("Results:", JSON.stringify(results, null, 2));
  } catch (err) {
    console.error("Error:", err.message);
  } finally {
    session.close();
  }
}

main();
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateGo(node *model.MibNode) string {
	return fmt.Sprintf(`package main

/*
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 */

import (
	"fmt"
	"log"
	"time"

	"github.com/gosnmp/gosnmp"
)

func main() {
	// Configure SNMP parameters
	params := &gosnmp.GoSNMP{
		Target:    "127.0.0.1",
		Port:      161,
		Community: "public",
		Version:   gosnmp.Version2c,
		Timeout:   time.Duration(10) * time.Second,
		Retries:   3,
	}

	// Connect
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect error: %%v", err)
	}
	defer params.Conn.Close()

	// Define OID to query
	oid := "%s"
	oids := []string{oid}

	// Perform SNMP GET
	fmt.Printf("Querying %%s (%s)...\n", oid)
	result, err := params.Get(oids)
	if err != nil {
		log.Fatalf("Get error: %%v", err)
	}

	// Process results
	for _, variable := range result.Variables {
		fmt.Printf("OID: %%s\n", variable.Name)
		fmt.Printf("Type: %%s\n", getTypeName(variable.Type))
		fmt.Printf("Value: %%v\n", variable.Value)
	}
}

// SNMP Walk example
func walkExample(params *gosnmp.GoSNMP, rootOid string) {
	fmt.Printf("\nWalking %%s...\n", rootOid)

	err := params.Walk(rootOid, func(pdu gosnmp.SnmpPDU) error {
		fmt.Printf("%%s = %%v\n", pdu.Name, pdu.Value)
		return nil
	})

	if err != nil {
		log.Printf("Walk error: %%v", err)
	}
}

func getTypeName(t gosnmp.Asn1BER) string {
	names := map[gosnmp.Asn1BER]string{
		gosnmp.Integer:          "Integer",
		gosnmp.OctetString:      "OctetString",
		gosnmp.Null:             "Null",
		gosnmp.ObjectIdentifier: "OID",
		gosnmp.Counter32:        "Counter32",
		gosnmp.Gauge32:          "Gauge32",
		gosnmp.TimeTicks:        "TimeTicks",
		gosnmp.Counter64:        "Counter64",
		gosnmp.IPAddress:        "IPAddress",
	}
	if name, ok := names[t]; ok {
		return name
	}
	return fmt.Sprintf("Unknown(%%d)", t)
}
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateJava(node *model.MibNode) string {
	return fmt.Sprintf(`/**
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 *
 * Dependencies: snmp4j library
 * Maven: <dependency><groupId>org.snmp4j</groupId><artifactId>snmp4j</artifactId><version>3.7.0</version></dependency>
 */

import org.snmp4j.*;
import org.snmp4j.event.ResponseEvent;
import org.snmp4j.mp.SnmpConstants;
import org.snmp4j.smi.*;
import org.snmp4j.transport.DefaultUdpTransportMapping;

public class SnmpQuery {

    private static final String HOST = "127.0.0.1";
    private static final int PORT = 161;
    private static final String COMMUNITY = "public";
    private static final String OID = "%s";

    public static void main(String[] args) throws Exception {
        // Create transport
        TransportMapping<?> transport = new DefaultUdpTransportMapping();
        transport.listen();

        // Create SNMP session
        Snmp snmp = new Snmp(transport);

        // Create target
        CommunityTarget<Address> target = new CommunityTarget<>();
        target.setCommunity(new OctetString(COMMUNITY));
        target.setAddress(new UdpAddress(HOST + "/" + PORT));
        target.setRetries(3);
        target.setTimeout(10000);
        target.setVersion(SnmpConstants.version2c);

        // Create PDU
        PDU pdu = new PDU();
        pdu.add(new VariableBinding(new OID(OID)));
        pdu.setType(PDU.GET);

        // Send request
        System.out.println("Querying " + OID + " (%s)...");
        ResponseEvent<?> response = snmp.send(pdu, target);

        // Process response
        if (response.getResponse() != null) {
            for (VariableBinding vb : response.getResponse().getVariableBindings()) {
                System.out.println("OID: " + vb.getOid());
                System.out.println("Value: " + vb.getVariable());
            }
        } else {
            System.out.println("No response received");
        }

        snmp.close();
    }
}
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateShell(node *model.MibNode) string {
	return fmt.Sprintf(`#!/bin/bash
#
# SNMP Query for: %s
# OID: %s
# Generated by SNMP MIB Explorer
#

HOST="127.0.0.1"
COMMUNITY="public"
OID="%s"

echo "=== SNMP GET ==="
echo "Querying $OID (%s)..."
snmpget -v2c -c "$COMMUNITY" "$HOST" "$OID"

echo ""
echo "=== SNMP WALK ==="
echo "Walking $OID..."
snmpwalk -v2c -c "$COMMUNITY" "$HOST" "$OID"

echo ""
echo "=== With verbose output ==="
snmpget -v2c -c "$COMMUNITY" -O n -O e "$HOST" "$OID"
`, node.Name, node.OID, node.OID, node.Name)
}

func sanitizeName(name string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9_]`)
	result := re.ReplaceAllString(name, "_")
	result = strings.ToLower(result)
	// Remove consecutive underscores
	re2 := regexp.MustCompile(`_+`)
	result = re2.ReplaceAllString(result, "_")
	// Remove leading/trailing underscores
	result = strings.Trim(result, "_")
	return result
}
