package service

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"snmp-mib-explorer/internal/model"
)

type GeneratorService struct{}

func NewGeneratorService() *GeneratorService {
	return &GeneratorService{}
}

// DeviceInfo represents a device for config generation
type DeviceInfo struct {
	Name      string `json:"name"`
	IP        string `json:"ip"`
	Port      int    `json:"port"`
	Community string `json:"community"`
	Version   string `json:"version"`
}

type GenerateConfigRequest struct {
	Collector string           `json:"collector"` // snmp-exporter, telegraf, categraf
	Version   string           `json:"version"`
	Nodes     []model.MibNode  `json:"nodes"`
	Community string           `json:"community"`
	MibRoot   string           `json:"mibRoot"`
	Devices   []DeviceInfo     `json:"devices"` // Selected devices for telegraf/categraf
}

func (s *GeneratorService) GenerateConfig(req *GenerateConfigRequest) string {
	// 参数验证
	if req.Collector == "" {
		return "# 错误: 未指定采集器类型 (collector)"
	}
	if len(req.Nodes) == 0 {
		return "# 错误: 未选择任何 OID 指标，请先从 MIB 树中选择需要采集的指标"
	}

	// Telegraf 和 Categraf 必须有设备信息
	if (req.Collector == "telegraf" || req.Collector == "categraf") && len(req.Devices) == 0 {
		return "# 错误: " + req.Collector + " 配置必须指定目标设备，请先添加并选择设备"
	}

	timestamp := time.Now().Format("2006-01-02 15:04:05")

	switch req.Collector {
	case "snmp-exporter":
		return s.generateSnmpExporter(req, timestamp)
	case "telegraf":
		return s.generateTelegraf(req, timestamp)
	case "categraf":
		return s.generateCategraf(req, timestamp)
	default:
		return fmt.Sprintf("# 错误: 不支持的采集器类型 '%s'，支持的类型：snmp-exporter, telegraf, categraf", req.Collector)
	}
}

func (s *GeneratorService) generateSnmpExporter(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# SNMP Exporter Configuration\n"))
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# MIB Root: %s\n", req.MibRoot))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("modules:\n")
	sb.WriteString("  default:\n")
	sb.WriteString("    walk:\n")

	for _, node := range req.Nodes {
		sb.WriteString(fmt.Sprintf("      - %s  # %s\n", node.OID, node.Name))
	}

	sb.WriteString("\n    metrics:\n")
	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		help := node.Description
		if help == "" {
			help = node.Name
		}
		// Escape quotes in help text
		help = strings.ReplaceAll(help, `"`, `\"`)

		sb.WriteString(fmt.Sprintf("      - name: %s\n", safeName))
		sb.WriteString(fmt.Sprintf("        oid: %s\n", node.OID))
		sb.WriteString(fmt.Sprintf("        type: gauge\n"))
		sb.WriteString(fmt.Sprintf("        help: \"%s\"\n", help))
	}

	sb.WriteString("\n    auth:\n")
	sb.WriteString("      community: " + community + "\n")

	return sb.String()
}

func (s *GeneratorService) generateTelegraf(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	// Build agents list from devices
	var agents []string
	if len(req.Devices) > 0 {
		for _, d := range req.Devices {
			port := d.Port
			if port == 0 {
				port = 161
			}
			agents = append(agents, fmt.Sprintf("\"udp://%s:%d\"", d.IP, port))
		}
		// Use first device's community if available
		if req.Devices[0].Community != "" {
			community = req.Devices[0].Community
		}
	} else {
		agents = []string{"\"udp://127.0.0.1:161\""}
	}

	var sb strings.Builder
	sb.WriteString("# Telegraf SNMP Input Configuration\n")
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# Devices: %d\n", len(req.Devices)))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("[[inputs.snmp]]\n")
	sb.WriteString("  ## Agent addresses to retrieve values from.\n")
	sb.WriteString(fmt.Sprintf("  agents = [%s]\n\n", strings.Join(agents, ", ")))
	sb.WriteString("  ## Timeout for each request.\n")
	sb.WriteString("  timeout = \"10s\"\n\n")
	sb.WriteString("  ## SNMP version; can be 1, 2, or 3.\n")
	sb.WriteString("  version = 2\n\n")
	sb.WriteString("  ## SNMP community string.\n")
	sb.WriteString(fmt.Sprintf("  community = \"%s\"\n\n", community))
	sb.WriteString("  ## Measurement name\n")
	sb.WriteString("  name = \"snmp\"\n\n")
	sb.WriteString("  ## Add fields to represent OID values\n")

	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		sb.WriteString(fmt.Sprintf("\n  [[inputs.snmp.field]]\n"))
		sb.WriteString(fmt.Sprintf("    name = \"%s\"\n", safeName))
		sb.WriteString(fmt.Sprintf("    oid = \"%s\"\n", node.OID))
		if node.Description != "" {
			sb.WriteString(fmt.Sprintf("    # %s\n", node.Description))
		}
	}

	sb.WriteString("\n  ## Add tables for table-based OIDs\n")
	sb.WriteString("  # [[inputs.snmp.table]]\n")
	sb.WriteString("  #   name = \"interface\"\n")
	sb.WriteString("  #   oid = \"IF-MIB::ifTable\"\n")

	return sb.String()
}

func (s *GeneratorService) generateCategraf(req *GenerateConfigRequest, timestamp string) string {
	community := req.Community
	if community == "" {
		community = "public"
	}

	// Build agents list from devices
	var agents []string
	if len(req.Devices) > 0 {
		for _, d := range req.Devices {
			port := d.Port
			if port == 0 {
				port = 161
			}
			agents = append(agents, fmt.Sprintf("\"%s:%d\"", d.IP, port))
		}
		// Use first device's community if available
		if req.Devices[0].Community != "" {
			community = req.Devices[0].Community
		}
	} else {
		agents = []string{"\"127.0.0.1:161\""}
	}

	var sb strings.Builder
	sb.WriteString("# Categraf SNMP Plugin Configuration\n")
	sb.WriteString(fmt.Sprintf("# Generated by SNMP MIB Explorer\n"))
	sb.WriteString(fmt.Sprintf("# Version: %s\n", req.Version))
	sb.WriteString(fmt.Sprintf("# Date: %s\n", timestamp))
	sb.WriteString(fmt.Sprintf("# Devices: %d\n", len(req.Devices)))
	sb.WriteString(fmt.Sprintf("# Metrics Count: %d\n\n", len(req.Nodes)))

	sb.WriteString("[[instances]]\n")
	sb.WriteString("  ## Interval for SNMP polling\n")
	sb.WriteString("  interval = \"60s\"\n\n")
	sb.WriteString("  ## Agent addresses\n")
	sb.WriteString(fmt.Sprintf("  agents = [%s]\n\n", strings.Join(agents, ", ")))
	sb.WriteString("  ## Timeout\n")
	sb.WriteString("  timeout = \"10s\"\n\n")
	sb.WriteString("  ## SNMP version (1, 2 for v2c, 3)\n")
	sb.WriteString("  version = 2\n\n")
	sb.WriteString("  ## Community string\n")
	sb.WriteString(fmt.Sprintf("  community = \"%s\"\n\n", community))
	sb.WriteString("  ## Labels to attach to all metrics\n")
	sb.WriteString("  labels = { job = \"snmp\" }\n\n")
	sb.WriteString("  ## Fields to collect\n")

	for _, node := range req.Nodes {
		safeName := sanitizeName(node.Name)
		sb.WriteString(fmt.Sprintf("\n  [[instances.field]]\n"))
		sb.WriteString(fmt.Sprintf("    name = \"%s\"\n", safeName))
		sb.WriteString(fmt.Sprintf("    oid = \"%s\"\n", node.OID))
	}

	sb.WriteString("\n  ## Table-based collection (optional)\n")
	sb.WriteString("  # [[instances.table]]\n")
	sb.WriteString("  #   name = \"interface\"\n")
	sb.WriteString("  #   oid = \"1.3.6.1.2.1.2.2\"\n")

	return sb.String()
}

type GenerateCodeRequest struct {
	Node     model.MibNode `json:"node"`
	Language string        `json:"language"` // python, javascript, go, java, shell
}

func (s *GeneratorService) GenerateCode(req *GenerateCodeRequest) string {
	switch req.Language {
	case "python":
		return s.generatePython(&req.Node)
	case "javascript":
		return s.generateJavaScript(&req.Node)
	case "go":
		return s.generateGo(&req.Node)
	case "java":
		return s.generateJava(&req.Node)
	case "shell":
		return s.generateShell(&req.Node)
	default:
		return fmt.Sprintf("// Unsupported language: %s", req.Language)
	}
}

func (s *GeneratorService) generatePython(node *model.MibNode) string {
	return fmt.Sprintf(`#!/usr/bin/env python3
"""
SNMP Query for: %s
OID: %s
Generated by SNMP MIB Explorer
"""

from pysnmp.hlapi import *

def snmp_get(host, community, oid):
    """Perform SNMP GET operation"""
    iterator = getCmd(
        SnmpEngine(),
        CommunityData(community),
        UdpTransportTarget((host, 161), timeout=10, retries=3),
        ContextData(),
        ObjectType(ObjectIdentity(oid))
    )

    errorIndication, errorStatus, errorIndex, varBinds = next(iterator)

    if errorIndication:
        print(f"Error: {errorIndication}")
        return None
    elif errorStatus:
        print(f"Error: {errorStatus.prettyPrint()} at {errorIndex}")
        return None
    else:
        for varBind in varBinds:
            return varBind[1].prettyPrint()
    return None

def snmp_walk(host, community, oid):
    """Perform SNMP WALK operation"""
    results = []
    for (errorIndication, errorStatus, errorIndex, varBinds) in nextCmd(
        SnmpEngine(),
        CommunityData(community),
        UdpTransportTarget((host, 161), timeout=10, retries=3),
        ContextData(),
        ObjectType(ObjectIdentity(oid)),
        lexicographicMode=False
    ):
        if errorIndication:
            print(f"Error: {errorIndication}")
            break
        elif errorStatus:
            print(f"Error: {errorStatus.prettyPrint()}")
            break
        else:
            for varBind in varBinds:
                results.append({
                    'oid': varBind[0].prettyPrint(),
                    'value': varBind[1].prettyPrint()
                })
    return results

if __name__ == "__main__":
    HOST = "127.0.0.1"
    COMMUNITY = "public"
    OID = "%s"

    print(f"Querying {OID} ({node_name})...")
    result = snmp_get(HOST, COMMUNITY, OID)
    print(f"Result: {result}")
`, node.Name, node.OID, node.OID)
}

func (s *GeneratorService) generateJavaScript(node *model.MibNode) string {
	return fmt.Sprintf(`/**
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 */

const snmp = require("net-snmp");

const HOST = "127.0.0.1";
const COMMUNITY = "public";
const OID = "%s";

// Create SNMP session
const session = snmp.createSession(HOST, COMMUNITY, {
  port: 161,
  timeout: 10000,
  retries: 3,
  version: snmp.Version2c
});

// SNMP GET
function snmpGet(oid) {
  return new Promise((resolve, reject) => {
    session.get([oid], (error, varbinds) => {
      if (error) {
        reject(error);
      } else {
        const results = varbinds.map(vb => ({
          oid: vb.oid,
          type: snmp.ObjectType[vb.type],
          value: vb.value.toString()
        }));
        resolve(results);
      }
    });
  });
}

// SNMP WALK
function snmpWalk(oid) {
  return new Promise((resolve, reject) => {
    const results = [];
    session.walk(oid, 20, (varbinds) => {
      varbinds.forEach(vb => {
        results.push({
          oid: vb.oid,
          type: snmp.ObjectType[vb.type],
          value: vb.value.toString()
        });
      });
    }, (error) => {
      if (error) {
        reject(error);
      } else {
        resolve(results);
      }
    });
  });
}

// Main execution
async function main() {
  try {
    console.log("Querying " + OID + " (%s)...");
    const results = await snmpGet(OID);
    console.log("Results:", JSON.stringify(results, null, 2));
  } catch (err) {
    console.error("Error:", err.message);
  } finally {
    session.close();
  }
}

main();
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateGo(node *model.MibNode) string {
	return fmt.Sprintf(`package main

/*
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 */

import (
	"fmt"
	"log"
	"time"

	"github.com/gosnmp/gosnmp"
)

func main() {
	// Configure SNMP parameters
	params := &gosnmp.GoSNMP{
		Target:    "127.0.0.1",
		Port:      161,
		Community: "public",
		Version:   gosnmp.Version2c,
		Timeout:   time.Duration(10) * time.Second,
		Retries:   3,
	}

	// Connect
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect error: %%v", err)
	}
	defer params.Conn.Close()

	// Define OID to query
	oid := "%s"
	oids := []string{oid}

	// Perform SNMP GET
	fmt.Printf("Querying %%s (%s)...\n", oid)
	result, err := params.Get(oids)
	if err != nil {
		log.Fatalf("Get error: %%v", err)
	}

	// Process results
	for _, variable := range result.Variables {
		fmt.Printf("OID: %%s\n", variable.Name)
		fmt.Printf("Type: %%s\n", getTypeName(variable.Type))
		fmt.Printf("Value: %%v\n", variable.Value)
	}
}

// SNMP Walk example
func walkExample(params *gosnmp.GoSNMP, rootOid string) {
	fmt.Printf("\nWalking %%s...\n", rootOid)

	err := params.Walk(rootOid, func(pdu gosnmp.SnmpPDU) error {
		fmt.Printf("%%s = %%v\n", pdu.Name, pdu.Value)
		return nil
	})

	if err != nil {
		log.Printf("Walk error: %%v", err)
	}
}

func getTypeName(t gosnmp.Asn1BER) string {
	names := map[gosnmp.Asn1BER]string{
		gosnmp.Integer:          "Integer",
		gosnmp.OctetString:      "OctetString",
		gosnmp.Null:             "Null",
		gosnmp.ObjectIdentifier: "OID",
		gosnmp.Counter32:        "Counter32",
		gosnmp.Gauge32:          "Gauge32",
		gosnmp.TimeTicks:        "TimeTicks",
		gosnmp.Counter64:        "Counter64",
		gosnmp.IPAddress:        "IPAddress",
	}
	if name, ok := names[t]; ok {
		return name
	}
	return fmt.Sprintf("Unknown(%%d)", t)
}
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateJava(node *model.MibNode) string {
	return fmt.Sprintf(`/**
 * SNMP Query for: %s
 * OID: %s
 * Generated by SNMP MIB Explorer
 *
 * Dependencies: snmp4j library
 * Maven: <dependency><groupId>org.snmp4j</groupId><artifactId>snmp4j</artifactId><version>3.7.0</version></dependency>
 */

import org.snmp4j.*;
import org.snmp4j.event.ResponseEvent;
import org.snmp4j.mp.SnmpConstants;
import org.snmp4j.smi.*;
import org.snmp4j.transport.DefaultUdpTransportMapping;

public class SnmpQuery {

    private static final String HOST = "127.0.0.1";
    private static final int PORT = 161;
    private static final String COMMUNITY = "public";
    private static final String OID = "%s";

    public static void main(String[] args) throws Exception {
        // Create transport
        TransportMapping<?> transport = new DefaultUdpTransportMapping();
        transport.listen();

        // Create SNMP session
        Snmp snmp = new Snmp(transport);

        // Create target
        CommunityTarget<Address> target = new CommunityTarget<>();
        target.setCommunity(new OctetString(COMMUNITY));
        target.setAddress(new UdpAddress(HOST + "/" + PORT));
        target.setRetries(3);
        target.setTimeout(10000);
        target.setVersion(SnmpConstants.version2c);

        // Create PDU
        PDU pdu = new PDU();
        pdu.add(new VariableBinding(new OID(OID)));
        pdu.setType(PDU.GET);

        // Send request
        System.out.println("Querying " + OID + " (%s)...");
        ResponseEvent<?> response = snmp.send(pdu, target);

        // Process response
        if (response.getResponse() != null) {
            for (VariableBinding vb : response.getResponse().getVariableBindings()) {
                System.out.println("OID: " + vb.getOid());
                System.out.println("Value: " + vb.getVariable());
            }
        } else {
            System.out.println("No response received");
        }

        snmp.close();
    }
}
`, node.Name, node.OID, node.OID, node.Name)
}

func (s *GeneratorService) generateShell(node *model.MibNode) string {
	return fmt.Sprintf(`#!/bin/bash
#
# SNMP Query for: %s
# OID: %s
# Generated by SNMP MIB Explorer
#

HOST="127.0.0.1"
COMMUNITY="public"
OID="%s"

echo "=== SNMP GET ==="
echo "Querying $OID (%s)..."
snmpget -v2c -c "$COMMUNITY" "$HOST" "$OID"

echo ""
echo "=== SNMP WALK ==="
echo "Walking $OID..."
snmpwalk -v2c -c "$COMMUNITY" "$HOST" "$OID"

echo ""
echo "=== With verbose output ==="
snmpget -v2c -c "$COMMUNITY" -O n -O e "$HOST" "$OID"
`, node.Name, node.OID, node.OID, node.Name)
}

func sanitizeName(name string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9_]`)
	result := re.ReplaceAllString(name, "_")
	result = strings.ToLower(result)
	// Remove consecutive underscores
	re2 := regexp.MustCompile(`_+`)
	result = re2.ReplaceAllString(result, "_")
	// Remove leading/trailing underscores
	result = strings.Trim(result, "_")
	return result
}

// ValidationResult represents the result of configuration validation
type ValidationResult struct {
	IsValid bool     `json:"isValid"`
	Errors  []string `json:"errors"`
	Warnings []string `json:"warnings"`
}

// ValidateConfig validates the generated configuration
func (s *GeneratorService) ValidateConfig(req *GenerateConfigRequest) *ValidationResult {
	result := &ValidationResult{
		IsValid:  true,
		Errors:   []string{},
		Warnings: []string{},
	}

	// Check for duplicate OIDs
	oidMap := make(map[string]string) // OID -> Name
	for _, node := range req.Nodes {
		if existingName, exists := oidMap[node.OID]; exists {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("重复的 OID: %s (出现在 %s 和 %s)", node.OID, existingName, node.Name))
		}
		oidMap[node.OID] = node.Name
	}

	// Check OID format
	for _, node := range req.Nodes {
		if !isValidOID(node.OID) {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("OID 格式无效: %s (%s)", node.OID, node.Name))
		}
	}

	// Validate based on collector type
	switch req.Collector {
	case "snmp-exporter":
		s.validateSnmpExporterConfig(req, result)
	case "telegraf":
		s.validateTelegrafConfig(req, result)
	case "categraf":
		s.validateCategrafConfig(req, result)
	}

	// Performance warnings
	if len(req.Nodes) > 100 {
		result.Warnings = append(result.Warnings,
			fmt.Sprintf("采集指标数量较多 (%d)，可能影响 SNMP 采集性能", len(req.Nodes)))
	}

	// Check for common problematic OIDs
	for _, node := range req.Nodes {
		if isHighOverheadOID(node.OID) {
			result.Warnings = append(result.Warnings,
				fmt.Sprintf("OID %s (%s) 可能产生大量数据，建议谨慎使用", node.OID, node.Name))
		}
	}

	return result
}

// validateSnmpExporterConfig validates SNMP Exporter configuration
func (s *GeneratorService) validateSnmpExporterConfig(req *GenerateConfigRequest, result *ValidationResult) {
	// Check community string
	if req.Community == "" {
		result.Warnings = append(result.Warnings, "未设置 Community 字符串，将使用默认值 'public'")
	}

	// Validate YAML syntax by generating and parsing
	config := s.generateSnmpExporter(req, time.Now().Format("2006-01-02 15:04:05"))
	if !isValidYAML(config) {
		result.IsValid = false
		result.Errors = append(result.Errors, "生成的 YAML 配置语法错误")
	}
}

// validateTelegrafConfig validates Telegraf configuration
func (s *GeneratorService) validateTelegrafConfig(req *GenerateConfigRequest, result *ValidationResult) {
	// Check devices
	if len(req.Devices) == 0 {
		result.Warnings = append(result.Warnings, "未选择目标设备，将使用默认地址 127.0.0.1:161")
	}

	// Validate IP addresses
	for _, device := range req.Devices {
		if !isValidIP(device.IP) {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("设备 IP 地址无效: %s (%s)", device.IP, device.Name))
		}
		if device.Port <= 0 || device.Port > 65535 {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("设备端口无效: %d (%s)", device.Port, device.Name))
		}
	}
}

// validateCategrafConfig validates Categraf configuration
func (s *GeneratorService) validateCategrafConfig(req *GenerateConfigRequest, result *ValidationResult) {
	// Similar validation as Telegraf
	if len(req.Devices) == 0 {
		result.Warnings = append(result.Warnings, "未选择目标设备，将使用默认地址 127.0.0.1:161")
	}

	for _, device := range req.Devices {
		if !isValidIP(device.IP) {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("设备 IP 地址无效: %s (%s)", device.IP, device.Name))
		}
		if device.Port <= 0 || device.Port > 65535 {
			result.IsValid = false
			result.Errors = append(result.Errors,
				fmt.Sprintf("设备端口无效: %d (%s)", device.Port, device.Name))
		}
	}
}

// isValidOID checks if an OID string is valid
func isValidOID(oid string) bool {
	if oid == "" {
		return false
	}
	// OID should start with a digit (0-9)
	if oid[0] < '0' || oid[0] > '9' {
		return false
	}
	// Check format: numbers separated by dots
	parts := strings.Split(oid, ".")
	for _, part := range parts {
		if part == "" {
			continue
		}
		// Each part should be a positive integer
		for _, ch := range part {
			if ch < '0' || ch > '9' {
				return false
			}
		}
	}
	return true
}

// isValidIP checks if an IP address is valid (basic check)
func isValidIP(ip string) bool {
	if ip == "" {
		return false
	}
	parts := strings.Split(ip, ".")
	if len(parts) != 4 {
		return false
	}
	for _, part := range parts {
		if len(part) == 0 || len(part) > 3 {
			return false
		}
		for _, ch := range part {
			if ch < '0' || ch > '9' {
				return false
			}
		}
		num := 0
		for _, ch := range part {
			num = num*10 + int(ch-'0')
		}
		if num > 255 {
			return false
		}
	}
	return true
}

// isValidYAML checks if a YAML string is valid
func isValidYAML(yamlStr string) bool {
	// Basic YAML validation
	// Check for proper indentation
	lines := strings.Split(yamlStr, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "  ") && strings.Contains(line, "  ") {
			// Check for mixed tabs and spaces
			if strings.Contains(line, "\t") && strings.Contains(line, "  ") {
				return false
			}
		}
	}
	return true
}

// isHighOverheadOID checks if an OID is known to produce large responses
func isHighOverheadOID(oid string) bool {
	// Common high-overhead OIDs
	highOverheadPrefixes := []string{
		"1.3.6.1.2.1.2.2",   // ifTable
		"1.3.6.1.2.1.4.20",  // ipAddrTable
		"1.3.6.1.2.1.4.21",  // ipRouteTable
		"1.3.6.1.2.1.4.22",  // ipNetToMediaTable
		"1.3.6.1.2.1.17.4",  // dot1dTpFdbTable
	}
	for _, prefix := range highOverheadPrefixes {
		if strings.HasPrefix(oid, prefix) {
			return true
		}
	}
	return false
}
